version: '3.1'

services:

  mongo:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  tornadomongo:
    image: tornadomongo:1.0.2
    ports:
      - 9000:9000
