# Use an official Python runtime as a parent image
#FROM --platform=linux/amd64 python:3.9
#ARG BASE_IMAGE=python:3.9-bullseye

#functioning one - Ubuntu 22.04
ARG BASE_IMAGE=ubuntu:jammy-20231128

FROM ${BASE_IMAGE}

EXPOSE 9000/tcp

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    curl \
    pip \
    python3-cffi \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    fonts-noto

RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt install -y nodejs
RUN npm install -g newman

COPY . /app
WORKDIR /app
RUN ls
RUN pip install --trusted-host pypi.python.org -r requirements.txt

ADD entrypoint.sh /app
RUN chmod +x /app/entrypoint.sh
#ENV PYTHONPATH /app

CMD ["/app/entrypoint.sh"]
#CMD ["python", "students_tornado.py", "&","&&","sleep","10","&&","newman","run","https://api.postman.com/collections/718114-86993b77-21dd-4210-ae54-2630affd0537?access_key=PMAT-01HW2YHXHNF4XYZ3HZCG7E127Q"]