name: MongoDB Tornado and Newman

on: [push]

jobs:
  build-mongo-custom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -f Dockerfile-postman . -t postman-mongodb-tests:$COMMIT_SHA

      #- name: Push image to GHCR
      #  run: |
      #    COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
      #    docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-postman-mongodb-tests:$COMMIT_SHA

      - name: Run the image with tests
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker run postman-mongodb-tests:$COMMIT_SHA
        

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

      #tornadomongo:
      #  image: ghcr.io/mialliedo/tornadomongo-private-postman-mongodb-tests:latest
      #  ports:
      #    - 9000:9000
