# https://github.com/supercharge/mongodb-github-action/blob/main/.github/workflows/main.yml
name: Dependent jobs

on: [push] #, pull_request]

jobs:
  mongodb-tornado:
    # needs: build-and-push-test-image-on-acr
    name: MongoDB and Tornado
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      tornadomongo:
        image: edotest.azurecr.io/${{ github.repository }}-test-image:latest
        ports:
          - 9000:9000
        env:
          URI: mongodb://root:example@mongo:27017/