# https://github.com/supercharge/mongodb-github-action/blob/main/.github/workflows/main.yml
name: Dependent jobs

on: [push] #, pull_request]



jobs:
  build-and-push-test-image-on-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}-test-image:latest
  mongodb-tornado:
    # needs: build-and-push-test-image-on-acr
    needs: build-and-push-test-image-on-dockerhub
    name: MongoDB and Tornado
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      tornadomongo:
        image: mialliedo/tornadomongo-private-test-image:latest
        ports:
          - 9000:9000
        env:
          URI: mongodb://root:example@mongo:27017/

    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: https://api.postman.com/collections/718114-8914ed27-a366-4b19-81a3-1a5cf443d5c0?access_key=PMAT-01HWFE7107BW8K0Q817C3CKD9P
