name: Unittests with MongoDB

on: [push]

jobs:
  build-mongo-custom:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.6
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: APP-DATABASE
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      #- name: Newman-healthcheck
      #  id: env-variables
      #  uses: ./
      - name: Unittest environment setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Unittest
        run: |
          python -m tornado.testing tests