name: Build Docker image version-txt versioning
on:
  push:
    branches:
      - main
      - version-txt-test

jobs:
  build-and-push-on-ghcr-with-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Build and Push the image to GHCR
        run: |
          export VERSION=$(cat version.txt)
          echo "Version: $VERSION"    
          docker build . -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$VERSION