# https://github.com/supercharge/mongodb-github-action/blob/main/.github/workflows/main.yml
name: Start MongoDB Server

on: [push] #, pull_request]

jobs:
  mongodb-tornado-newman:
    name: Start MongoDB Server v${{ matrix.mongodb-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']#,'4.0', '4.2', '4.4', '5.0', '6.0']
        python-version: ['3.9']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

