# https://github.com/supercharge/mongodb-github-action/blob/main/.github/workflows/main.yml
name: Start MongoDB Server

on: [push] #, pull_request]

jobs:
  mongodb-tornado-newman:
    name: MongoDB v${{ matrix.mongodb-version }}-Python v${{ matrix.python-version }}-Node vv${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']#,'4.0', '4.2', '4.4', '5.0', '6.0']
        python-version: ['3.9']
        node-version: ['16']

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Install Newman dependency
        run: |
          npm install --prefix tests/postman/
